### ISSUE TITLE
Windows Zip file is invalid

### ISSUE THREAD

**Issue by stocksnut** [plotly/falcon-sql-client#126]
When I try to open the 32-bit or 64-bit versions, I get the error "Windows cannot open the folder.  The Compressed Folder is invalid"

**Comment by chriddyp** [comment]
Thanks for reporting! Which programming are you using to unzip the file? I was able to unzip it with 7zip on a windows machine.

**Comment by chriddyp** [comment]
Another error that was reported:
> An unexpected error is keeping you from copying the file. Error 0x800040005: Unspecified error. natives_blob.bin, Type: BIN File.

The issue here seems to be related to the presence of BIN files inside the zip file.

**Comment by alexandresobolevski** [comment]
The[ latest release ](https://github.com/plotly/plotly-database-connector/releases/tag/1.0.3)uses installation wizards for Windows and Mac. Downloading and installing has been tested on both systems. I will close this issue for now.

**Comment by RCura** [comment]
On windows, using v2.3.2, the zip still isn't correct : some of the archived paths are too long, and 7zip/windows native explorer can't unzip those.

**Comment by n-riesco** [comment]
@RCura Thank you for reporting this. It looks like we've lost the windows installer somewhere between v1 and v2.

**Comment by n-riesco** [comment]
Closed via https://github.com/plotly/falcon-sql-client/releases/tag/v2.3.3-beta1
