### ISSUE TITLE
MsSQL Express Compatibility

### ISSUE THREAD

**Issue by ArturoAguileraV** [plotly/falcon-sql-client#138]
I'd like to know if the Plotly Database Connector (when doing a MsSQL connection) supports a **MSSQL EXPRESS EDITION** database.

I tried to connect using the "sa" username and its password but nothing happened. It gives me the error:
**failed to connect to [hostname]:[PortNumber] - connect ECONNREFUSED [my IP address]:[PortNumber]**
This are my inputs:

- Username: **sa**
- Password: **mypassword**
- Host: **myHost**
- Port: (I left this port blank)
- Database: **myDB**

So, does it is compatible?

**Comment by alexandresobolevski** [comment]
Hi! After some searching it seems the connector currently does not support MSSQL EXPRESS ([relevant sequelize issue](https://github.com/sequelize/sequelize/issues/3097#issuecomment-73798671)) but it would it should be an easy fix. 

Relevant code in database-connector https://github.com/sequelize/sequelize/issues/3097#issuecomment-73798671
A new option 'instanceName' should be provided.

We welcome contributions from the community and will be glad to review them and work on them to include them in the connector.

**Comment by ArturoAguileraV** [comment]
Forgive my ignorance but... I searched in all the project and I just don't get to know which path does contains the **sequelize** connector, also, I downloaded the project and just can't make it start (most of it because I don't even know how to do it).

Thanks for your attention! :)

**Comment by alexandresobolevski** [comment]
Hey! Thanks you for getting your hands dirty :P

What did you try exactly to run it and how did it fail?

The following commands should get you up and running. 

```
npm install
npm run build
npm run start
```

**Comment by ArturoAguileraV** [comment]
Hey Alexandre! I'm happy to tell you that I got myself a big cup of coffee and finally found the file you kindly referenced to me, so, I made the changes in my application and it worked!

In my connection-manager.js which is located in _plotly-database-connector/resources/app/node_modules/sequelize/lib/dialects/mssql/connection-manager.js_ I just added **instanceName: 'SQLEXPRESS'** and everything worked fine!

Thank you again, for your consideration to answer my questions. I also made a [question] in(http://stackoverflow.com/questions/42589886/plotly-and-sql-server-express-compatibility) StackOverflow. And pasted the answer there.

**Comment by alexandresobolevski** [comment]
If you wish, you could create a branch in this repository and make a PR that would add that `instanceName` parameter as one of the inputs the user gives when he/she selects Microsoft SQL as the database to which it has to connect. This way others will only have to enter in the user interface without having to change the source code. I can help you with reviewing the PR. It should be quite simple. 

This is the place where it could be added in the front end https://github.com/plotly/plotly-database-connector/blob/master/app/constants/constants.js#L16
And  we can read that input in the back end here https://github.com/plotly/plotly-database-connector/blob/master/backend/persistent/datastores/Sql.js#L14

**Comment by ArturoAguileraV** [comment]
I just did it, I hope that's the correct way to do it.

I'd appreciate if you told me if i did it right or wrong :)

**Comment by n-riesco** [comment]
@ArturoAguileraV The project has been quite since your last comment (sorry about that). But now a new version is about to be released that includes a fix for this issue. You can download a prerelease. Please, let us know if you have any issues:
https://github.com/plotly/falcon-sql-client/releases/tag/v2.3-pre

**Comment by n-riesco** [comment]
Fixed in https://github.com/plotly/falcon-sql-client/releases/tag/v2.3.2
