### ISSUE TITLE
Windows installer .zip for V2.0.2 is invalid

### ISSUE THREAD

**Issue by rachelruijiayang** [plotly/falcon-sql-client#152]
Hi, I tried to download and extract windows-plotly-database-connector.zip from https://github.com/plotly/plotly-database-connector/releases/tag/v2.0.2, but the .zip is invalid. Here is the error message I got:
![windows-invalid](https://user-images.githubusercontent.com/8990918/27558169-5d2ee4ee-5a8a-11e7-8d57-c1a14a2e9d6e.png)

Text: The Compressed (zipped) Folder ...windows-plotly-database-connector.zip is invalid

Is anyone else getting this issue? If so, approximately when will a new .zip file be posted? If not, what am I doing incorrectly?

**Comment by chriddyp** [comment]
Thanks for reporting @rachelruijiayang ! I swore that this zip worked, so sorry about this. @bcdunbar - could you try this release download on your machine?

**Comment by chriddyp** [comment]
@rachelruijiayang @bcdunbar - Here's a link to the generated app build: https://ci.appveyor.com/project/AppVeyorDashAdmin/plotly-database-connector/build/job/bkh14v8eiqorv68m/artifacts. I usually just upload that build to the releases page. Could one or both of you verify if the zip file at https://ci.appveyor.com/project/AppVeyorDashAdmin/plotly-database-connector/build/job/bkh14v8eiqorv68m/artifacts works?

**Comment by bcdunbar** [comment]
It works but requires using 7zip or another file archiver to unzip.

**Comment by rachelruijiayang** [comment]
Thanks @bcdunbar! I was able to extract the file using 7zip and run the DB connector.

However, now I am having problems with authentication; after entering my username and clicking "Authorize Connector", the authentication window gets stuck on the blank screen with URL `http://localhost:9494/oauth2/callback#access_token=[my_access_token]&token_type=Bearer&state=&expires_in=31622400&scope=read+write+create`

Video: https://www.youtube.com/watch?v=6XSegCPXfgQ

**Comment by chriddyp** [comment]
Thanks for reporting @rachelruijiayang ! I'm not quite why the window isn't closing there. I suspect that the request finished correctly, it just didn't close the window. If you close and reopen the app, and re-enter your username, does it take you to the "Set Up Connections" screen?

**Comment by rachelruijiayang** [comment]
Ah, so it turns out I spelled my username wrong in the video I linked, but I tried again with the right username and the authentication window still gets stuck on the blank screen.

I also downloaded the Linux DB Connector, which allows me to log in and get to the "Set Up Connections" screen.

Here are screenshots of network activity on the page after Cancel/Authorize
![linuxauthorize](https://user-images.githubusercontent.com/8990918/27599617-531f1c1e-5b37-11e7-88d7-c24e1d2409b7.png)

Linux (successful authorization):
![linuxauthorized](https://user-images.githubusercontent.com/8990918/27599665-7e18355e-5b37-11e7-85a7-ece6366f08ff.png)

Windows (blank screen):
![windowsoauth](https://user-images.githubusercontent.com/8990918/27599630-62517ba0-5b37-11e7-95b4-1ae897389882.png)

**Comment by Saumya-Agrawal** [comment]
I have the same issue. After authentication I am directed to the same blank screen.

**Comment by n-riesco** [comment]
@rachelruijiayang @Saumya-Agrawal  You can download a prerelease with a fix here, please let us know if you have any issues:
https://github.com/plotly/falcon-sql-client/releases/tag/v2.3-pre

**Comment by n-riesco** [comment]
Fixed in https://github.com/plotly/falcon-sql-client/releases/tag/v2.3.2
