### ISSUE TITLE
Blank Grey Screen - Console Error - react-dd-menu

### ISSUE THREAD

**Issue by Fishy49** [plotly/falcon-sql-client#182]
After authenticating, the app shows a blank grey screen.

In the developer tools, I see:
"Uncaught Error: Cannot find module "react-dd-menu"

Running Windows 8.1 64x

![image](https://user-images.githubusercontent.com/5632528/30751133-10c890e4-9f7e-11e7-9251-9773e8c13ded.png)

**Comment by jackparmer** [comment]
We're not using `react-dd-menu` anymore, I took it out here:
https://github.com/plotly/plotly-database-connector/commit/8597c9b8e6941a574d75a8fbea2aac19912b0d00
We'll have a new build in the next few days and hopefully that will fix this.

**Comment by Fishy49** [comment]
Fantastic, thanks for the response! Looking forward to trying this out.

**Comment by jackparmer** [comment]
It's going to be worth the wait :) Huge update coming soon:

![big_app_screencast](https://user-images.githubusercontent.com/1865834/30830371-dadf68e0-a211-11e7-9ff8-fcda0c72bb4c.gif)

**Comment by owensj8** [comment]
I have the same issue. Is there an ETA on when the new build will be out? From what I can tell, this tool looks great. Thanks

**Comment by jackparmer** [comment]
@owensj8 Hopefully next week

**Comment by KasperKimose** [comment]
I have the same issue. Is the new build out? Thanks

**Comment by adeleglise** [comment]
Hi, same issue here

**Comment by jackparmer** [comment]
@owensj8 @KasperKimose @adeleglise @Fishy49  You can download a prerelease with a fix here, please let us know if you have any issues:
https://github.com/plotly/falcon-sql-client/releases/tag/v2.3-pre

**Comment by n-riesco** [comment]
Fixed in https://github.com/plotly/falcon-sql-client/releases/tag/v2.3.2
