### ISSUE TITLE
Postgres only supports public schema

### ISSUE THREAD

**Issue by snooc** [plotly/falcon-sql-client#224]
The queries for Postgres tables limits to only the public schema. 

- https://github.com/plotly/falcon-sql-client/blob/master/backend/persistent/datastores/Sql.js#L36
- https://github.com/plotly/falcon-sql-client/blob/master/backend/persistent/datastores/Sql.js#L169

I'm open to create a PR, but my attempts to run the application locally have been unsuccessful because of OAuth issues when connecting to the plotly cloud.

**Comment by n-riesco** [comment]
Could you open an issue for the problem you see connecting to plotly cloud?
I'm now looking into https://github.com/plotly/falcon-sql-client/blob/master/backend/plugins/authorization.js and I may be able to help.

**Comment by snooc** [comment]
Thanks @n-riesco. I filed https://github.com/plotly/falcon-sql-client/issues/227. I think that may be the issue that I am seeing.

**Comment by n-riesco** [comment]
@snooc I fixed this issue for Redshift in PR #256, but as the same solution is valid for Postgres, I've also fixed it for Postgres.
