### ISSUE TITLE
[Link Broken] Download Falcon for Windows

### ISSUE THREAD

**Issue by OmaymaS** [plotly/falcon-sql-client#240]
[Download Falcon for Windows](https://github.com/plotly/falcon-sql-client/blob/master/plot.ly/free-sql-client-download) in README.md is broken. It leads to nothing.

**Comment by n-riesco** [comment]
Both Windows and Mac links are broken.

Here's the link for windows https://github.com/plotly/falcon-sql-client/releases/download/v2.3.2/windows-falcon-sql-client.zip .

It also looks like we've lost the windows installer somewhere between v1 and v2. Until we restore it, you'll need to install [7-Zip](http://www.7-zip.org/) to unzip the file above and find Falcon's executable in folder `/release/Windows-64bit/Falcon SQL Client-win32-x64/`.

**Comment by n-riesco** [comment]
Related #126

**Comment by jackparmer** [comment]
Whoops, sorry guys. Fixed the links in the README: https://github.com/plotly/falcon-sql-client/commit/b7881d336510ca6f9ebd41cd618d6eb592ea286a
