### ISSUE TITLE
Don't grey out `*.sqlite*` paths

### ISSUE THREAD

**Issue by johnmyleswhite** [plotly/falcon-sql-client#241]
In the "Path to SQLite File" window, files that end in `.db` are not greyed out and can be clicked on. Files that end in `.sqlite` or `.sqlite3` are greyed out and can't be clicked on. See https://stackoverflow.com/questions/808499/what-is-the-best-extension-name-sqlite-database-files for examples of the other file extensions.

**Comment by n-riesco** [comment]
@johnmyleswhite Thank you for the report. It looks like Chris already has a fix for it. We'll merge the PR as soon as we have it tested.

**Comment by n-riesco** [comment]
Related #41
