### ISSUE TITLE
Crash on startup - Windows 7

### ISSUE THREAD

**Issue by jkornblum** [plotly/falcon-sql-client#243]
I downloaded file from the link [here](https://plot.ly/free-sql-client-download/)
I unzipped, navigated to .exe, and opened it.

I get this error
![falcon-err](https://user-images.githubusercontent.com/5368903/32757081-3b748796-c8a3-11e7-85e3-80f0e723811a.png)

This process also differs from the [docs ](https://help.plot.ly/database-connectors/personal-login/#step-3-install-the-app-windows) which say that I should be downloading an installer and it will install falcon on my machine.

I'm glad to take a look into the error but it will probably be fixed by the time I can get around to it :smile:

**Comment by n-riesco** [comment]
It looks like the zip file wasn't unzipped fully.

**Comment by n-riesco** [comment]
It looks like the zip file wasn't unzipped fully (this is a know issue #126). You need to install [7-zip](http://www.7-zip.org/).

Please, let us know if using 7-zip to unzip [windows-falcon-sql-client.zip](https://github.com/plotly/falcon-sql-client/releases/download/v2.3.2/windows-falcon-sql-client.zip] works for you.

**Comment by n-riesco** [comment]
Closed via https://github.com/plotly/falcon-sql-client/releases/tag/v2.3.3-beta1
