### ISSUE TITLE
Tables within schema not visible in side-panel when using Redshift as a data source

### ISSUE THREAD

**Issue by aaronfowles** [plotly/falcon-sql-client#246]
Tables within a schema other than public are not visible in Query side-panel when using Redshift as a data source. However, tables within schemas other than public are queryable if the user knows the name of the table(s) beforehand.

**Comment by n-riesco** [comment]
@aaronfowles That's the intended behaviour. What would be the use-case for querying non-public tables?

@jackparmer Is this something we want to support?

**Comment by aaronfowles** [comment]
@n-riesco You don't want to support the following use-case?

`SELECT * FROM app_one_schema.sessions;`
`SELECT * FROM app_two_schema.sessions;`

Where `app_one_schema` has been created to allow for seperation (perhaps I have multiple apps who share the same business data model but I want to seperate their data into different schemas.)

Falcon looks like a great tool but I'd need to stick with my current SQL client if supporting this use-case isn't in the roadmap.

**Comment by n-riesco** [comment]
@aaronfowles Oh I completely misunderstood you. What you're requesting is the ability to set a schema, isn't it?

Yes, this is doable. In fact, we are already planning to implement the same feature for Postgres. See #224 .

**Comment by aaronfowles** [comment]
@n-riesco Ah, yes - that functionality would be great. I'm now following #224 so will keep an eye on the outcome of that. Thanks!
