### ISSUE TITLE
Using R functions/packages in a query

### ISSUE THREAD

**Issue by joaoplm** [plotly/falcon-sql-client#271]
Hi, I was just thinking, there is a way to use the R functions from R packages when writing a query?

For exemple I want to do this:   Select cor(T.a,T.b,T.c) from table as T

Where cor() is the correlation function from R, and T.a, T.b, T.c are numeric columns in the table.

In SQL we already have AVG(), MIN(), MAX().  I want to use the R functions like cor()

Whatt you think?

**Comment by jackparmer** [comment]
Hi @joaoplm , Falcon will probably never support an R kernel unfortunately. 

I recommend running R in [nteract](https://nteract.io/) and query MySQL from there, see https://moderndata.plot.ly/connecting-r-to-mysql-mariadb/ for example
