### ISSUE TITLE
Connecting to postgresql with a table that have a capital letter in it make Falcon crash

### ISSUE THREAD

**Issue by Simobain** [plotly/falcon-sql-client#273]
I have a table "Capitalize". The automatic request fails because it does not use the " around table name.
After that i'm not able to run another query.

**Comment by n-riesco** [comment]
This is already fixed in master. Here's the instructions to build master, if you'd like to try (requires `node@6` and `yarn@1`):

```
$ git clone https://github.com/plotly/falcon-sql-client.git
$ cd falcon-sql-client
$ yarn install
$ yarn run rebuild:modules:electron
$ yarn run build
$ yarn start
```
