### ISSUE TITLE
table preview shows 1000 rows, whereas sample query requests only 10 rows

### ISSUE THREAD

**Issue by n-riesco** [plotly/falcon-sql-client#283]
![image 1](https://user-images.githubusercontent.com/6199391/33288693-0e619f4c-d3b5-11e7-875e-72c96e534e35.png)

**Comment by chriddyp** [comment]
and i actually only noticed this for SQLite, did not see this happen for IBMDB2

**Comment by n-riesco** [comment]
I think this is just a mismatch between https://github.com/plotly/falcon-sql-client/blob/42f07a27fe42b10bfb576d4761c2825c72566ff0/app/actions/sessions.js#L359-L386 and the code that sets the sample query.
