### ISSUE TITLE
Document location of log file

### ISSUE THREAD

**Issue by n-riesco** [plotly/falcon-sql-client#287]
@tarzzz @jackparmer  @chriddyp How about having a widget to display the log entries under the FAQ tab?

**Comment by jackparmer** [comment]
👍 sounds great to me
Basically impossible for lay users to efficiently report bugs otherwise

**Comment by n-riesco** [comment]
The location of the log file is now documented in [CONTRIBUTING.md](https://github.com/plotly/falcon-sql-client/blob/master/CONTRIBUTING.md).

Open issue #346 to continue the discussion to implement a way for users to view the log messages.
