### ISSUE TITLE
elasticsearch: handle case when user forgets to set port number

### ISSUE THREAD

**Issue by n-riesco** [plotly/falcon-sql-client#317]
See https://github.com/plotly/falcon-sql-client/issues/316#issuecomment-351370001

**Comment by shannonlal** [comment]
Nicolas,
As I mentioned in the original issue (#316 ) there might be an issue with using NGINX infront of Elastic Search.  I looked at the code last night and there might be an issue with the port.  I can run some tests tonight but I think if we can make the port optional (to support NGINX) this could solve the problem.  I will update this a little later tonight.

Thanks

**Comment by shannonlal** [comment]
Before we go and enforce the port with Elastic Search I think it might be a good idea to leave it as optional.  I am working my way through a related ElasticSearch issue (#316 ) and by making the port optional it is allowing me to connect to ElasticSearch cluster behind a NGINX server.

**Comment by n-riesco** [comment]
No, that's not what I mean.

At the moment, when Falcon connects to an elasticsearch server, it requests `_cat/indices`. Unfortunately, the server replies to this request even if the port number isn't set.

We need a more robust way to confirm the user has given us the right URL (regardless of whether that URL has a port number or not).

**Comment by shannonlal** [comment]
Ok makes sense.  If you want help fixing this let me know.  As I mentioned in issue #316 I am currently working my way through Elasticsearch.js to figure out what is causing the 400 error.

**Comment by shannonlal** [comment]
I was looking back at this issue and I was able to get ElasticSearch back up and running.  I wanted to see about solutions to validate the url.  Would you be looking for something like performing a regex evaluation of the url string?  Or would you like a solution which tries to connect to the ElasticSearch server and validate that it is up and running?

If it is the regex expression, I can throw together a regex expression and a PR pretty quickly

**Comment by n-riesco** [comment]
@shannonlal I'm working on this connector in PR #343 (I'll address this issue there).
