### ISSUE TITLE
pruning obsolete branches

### ISSUE THREAD

**Issue by n-riesco** [plotly/falcon-sql-client#325]
cc/ @tarzzz @chriddyp @jackparmer @bpostlethwaite @rmoestl 

Here's a list of branches that look obsolete.
Please, could you go through the list?

If you find that a branch is yours and you don't need it any longer,
please, could you tick it here and I'll delete it?

If you see any branches ticked for removal that you'd like to keep,
please, comment here.

## Branches to keep:
- 2.4-onprem (used for On-Prem 2.3.0)
- 2.2-release (used for On-Prem 2.2.0)

## Branches to prune:
- [ ] add-authentication
- [x] add-download
- [x] allow-oauth-uri-auth-exception
- [x] auto-add-to-allowed-users
- [x] circle2
- [x] electron-oauth-update
- [x] eslint-fixes-in-app
- [x] eslint-remaining-fixes
- [x] fix-appveyor
- [ ] livy
- [x] merge-jps-thing
- [x] migrate-webpack
- [x] mssql-options-old-build
- [x] n-riesco-travis-zip-only-installer
- [x] onprem-2.3-fixes
- [x] release-v2.4.0
- [ ] setup-hadoop-spark-test-db
- [x] tests-improve-error-messages
- [x] trying-to-api
- [x] usePlotlyDataSetsInDB2
- [x] v2.3-onprem
- [x] v2.3.2-onprem
- [x] yarn-sql-editor
- [x] yo-gaba-gaba

**Comment by chriddyp** [comment]
i don't need any of my branches, prune away!

**Comment by jackparmer** [comment]
Prune away! Thanks for tidying up the place!

**Comment by n-riesco** [comment]
@bpostlethwaite I'm going to delete `usePlotlyDataSetsInDB2` (since it's been already merged).

**Comment by n-riesco** [comment]
@tarzzz can you confirm you don't need the following branches that have unmerged commits?
- add-authentication
- setup-hadoop-spark-test-db
- livy
