### ISSUE TITLE
Support CSV file upload

### ISSUE THREAD

**Issue by jackparmer** [plotly/falcon-sql-client#349]
This [blog post review](https://blog.ouseful.info/2017/11/15/recent-releases-plotly-falcon-sql-client-and-the-remarkable-datasette-sqlite2api-generator/) of Falcon recommended CSV file upload so Falcon can be more on-par with something like Tableau Public. Seems like a useful idea and easy to add.

@nicolaskruchten recommends http://papaparse.com/

**Comment by nicolaskruchten** [comment]
Nice! Does the PR that closed this actually allow a user with local CSV to query it or must it be uploaded to a URL?

**Comment by n-riesco** [comment]
@nicolaskruchten No, just URLs. I've opened #383 to discuss how to implement uploading user's CSV files.
