### ISSUE TITLE
Replace chart editor with react-plotly.js-editor

### ISSUE THREAD

**Issue by jackparmer** [plotly/falcon-sql-client#350]
~`react-pivottable.js`~ `react-plotly.js-editor` has all of the ability of the current Falcon chart editor, plus many more features and is better tested: ~https://react-pivottable.js.org/~ https://plotly.github.io/react-plotly.js-editor/

Could also use this opportunity to automatically disable charting when more than ~100k rows are retrieved, which I believe may be the issue here: https://github.com/plotly/falcon-sql-client/issues/309

**Comment by shannonlal** [comment]
:thumbsup:

**Comment by jackparmer** [comment]
Here's a mock of how this might look based on [`react-plotly.js-editor`](https://plotly.github.io/react-plotly.js-editor/) so far:

![image](https://user-images.githubusercontent.com/1865834/36695186-8d97baee-1b0e-11e8-93a2-1e4d499d006c.png)
