### ISSUE TITLE
the dialog box for `path to database` does not display .db files on windows

### ISSUE THREAD

**Issue by alexandresobolevski** [plotly/falcon-sql-client#41]

**Comment by cldougl** [comment]
does anyone have any more info on this issue? I'm not seeing it with the [v2.3 release]()
but just want to make sure there weren't specific steps to reproduce? https://github.com/plotly/falcon-sql-client/releases/tag/v2.3-pre

**Comment by chriddyp** [comment]
@cldougl - this refers to the SQLite connection which basically just loads a sqlite `.db` file from the file system. On Mac, clicking on the "path" setting should open up the native mac file explorer, allowing you to select a sqlite file from your filesystem. This wasn't working on Windows systems - the native windows file explorer didn't open. I'm not sure if this has been fixed or not.

**Comment by cldougl** [comment]
Thanks for clarifying @chriddyp 
Looks like this is still an issue, the windows file explorer opens but only folders are visible (not files i.e the .db files)
Here you should see a test.db file:


like you do on the mac:
<img width="1273" alt="screen shot 2017-10-31 at 6 40 19 pm" src="https://user-images.githubusercontent.com/2789078/32252297-2c45a3aa-be6b-11e7-8ae0-9289bac387c0.png">

**Comment by n-riesco** [comment]
Closed #41 via #242.
