### ISSUE TITLE
API domain misconfiguration for On-Premise

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/falcon-sql-client#428]
Configuring the falcon desktop app to point to an On-Premise URL does not update the API domain used in the authorization request, resulting in the following error: 

**Yikes! An error occurred while trying to authorize.
Error: User was not found at https://api.plot.ly** 

![image](https://user-images.githubusercontent.com/1909107/39429020-8bcf3438-4c57-11e8-9802-dfa84e5fa20c.png)

**Expected behaviour:** 

1) The API domain is also configurable / defaults to be the same as the On-Premise base domain.

or

2) On-Premise support is removed from the desktop app in favour of clients using the hosted Falcon client. 

fyi @n-riesco @cldougl @chriddyp

**Comment by n-riesco** [comment]
@tarzzz Is this issue the same as #306?

**Comment by tarzzz** [comment]
Yes, It's the same issue.. !!

**Comment by BRONSOLO** [comment]
OK, great - I didn't see #306. Closing this issue in favour of that one.
