### ISSUE TITLE
Why is it always set chart settings?

### ISSUE THREAD

**Issue by zhaodagang** [plotly/falcon-sql-client#430]
I download a exe programmer.
After installing it , always show chart settings.

https://user-images.githubusercontent.com/6199391/37359812-782f9a1c-26e6-11e8-9b3f-e48275e62271.gif

How it show this about charts ?
https://raw.githubusercontent.com/plotly/falcon-sql-client/master/static/images/falcon_hero.gif

**Comment by n-riesco** [comment]
You need to provide the credentials to connect to your database. Like this:

![peek 2018-05-08 16-54](https://user-images.githubusercontent.com/6199391/39768224-8fb4c358-52e0-11e8-8cf3-19d9c4543e74.gif)

**Comment by zhaodagang** [comment]
When i am setting chart setting, why has not save button ?

2018-05-10 

zdg8882000 



发件人：Nicolas Riesco <notifications@github.com>
发送时间：2018-05-08 23:57
主题：Re: [plotly/falcon-sql-client] Why is it always set chart settings? (#430)
收件人："plotly/falcon-sql-client"<falcon-sql-client@noreply.github.com>
抄送："Mr Zhao"<zdg8882000@163.com>,"Author"<author@noreply.github.com>

You need to provide the credentials to connect to your database. Like this:

**Comment by zhaodagang** [comment]
I connect database that is successfult .
I finished set chart settings .
Next time i open the app, let me make the Settings again.
Why??

**Comment by zhaodagang** [comment]
@n-riesco

**Comment by zhaodagang** [comment]
[day09  express框架.txt](https://github.com/plotly/falcon-sql-client/files/1994245/day09.express.txt)

**Comment by jackparmer** [comment]
Please ask usage questions at https://community.plot.ly/c/falcon-sql-client

**Comment by n-riesco** [comment]
- Link to the question on the forum: https://community.plot.ly/t/why-is-it-always-set-chart-settings/10567
- Opened issue #470 to discuss alternative behaviour.
