### ISSUE TITLE
Tables on the left hand side should be in their own container

### ISSUE THREAD

**Issue by MiConnell** [plotly/falcon-sql-client#434]
The tables on the left side of the query window should be in their own container so that you can scroll within that and not have to scroll away from the display when searching for a table.

**Comment by n-riesco** [comment]
Thank you for opening this issue!
This issue is fixed in https://github.com/plotly/falcon-sql-client/commit/010f96ce5f9fe09e6d7bc69b7f5ae6ad92def204 and will be included in the next release.
