### ISSUE TITLE
Why is it always set chart settings?

### ISSUE THREAD

**Issue by zhaodagang** [plotly/falcon-sql-client#435]
@n-riesco, @shannonlal 
I connect database that is successfult .
I finished set chart settings .Like this
![11](https://user-images.githubusercontent.com/33817963/39977869-493175c8-576f-11e8-8da7-801e0cdccb39.jpg)

Next time i open the app, let me make the Settings again.
I think like this.
![12](https://user-images.githubusercontent.com/33817963/39977878-4f282094-576f-11e8-8d9d-c2cecfb3d8f1.jpg)

**How should i will do?**

**Comment by jackparmer** [comment]
Please ask usage questions at https://community.plot.ly/c/falcon-sql-client
