### ISSUE TITLE
MSSQL: Database table overview wrong

### ISSUE THREAD

**Issue by pabucur** [plotly/falcon-sql-client#462]
Using the Falcon SQL Client v2.8.0 under Windows 7 and connecting to a Microsoft SQL Server where multiple databases reside, I get the wrong table overview for the database. The tables shown and the corresponding columns in the dropdown correspond to other databases present on the server. Queries on the 'correct' database, the one I actually connected to, work.

**Comment by n-riesco** [comment]
Please, could you check what errors are reported in the log file `%USERPROFILE%\.plotly\connector/log.log`?

In particular, I'm interested in errors with the responses to `sql-tables` and `sql-schemas`.

**Comment by n-riesco** [comment]
Oh! it looks like when we get the tables schemas we don't filter by database name.

Currently, we are using this query to build the overview:

```sql
                SELECT T.name AS Table_Name, C.name AS Column_Name, P.name AS Data_Type
                FROM sys.objects AS T
                   JOIN sys.columns AS C ON T.object_id = C.object_id
                   JOIN sys.types AS P ON C.system_type_id = P.system_type_id
                WHERE T.type_desc = 'USER_TABLE';
```

After some experimentation, it looks like a query like this works for me

```sql
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_catalog = '${database}'
ORDER BY table_name
```

@pabucur please, could you check whether the above query works for you? You need to replace `${database}` by your database name.

**Comment by pabucur** [comment]
@n-riesco The query works, inserting the name of my database between the commas
