### ISSUE TITLE
Linux's tar.gz is gzipped twice

### ISSUE THREAD

**Issue by victornoel** [plotly/falcon-sql-client#471]
Hi,

It seems that the tar.gz for linux in the release tab has been gzipped twice instead of once.

See:
```
➜  file linux-falcon-v2.8.0.tar.gz 
linux-falcon-v2.8.0.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT), original size 98259368
➜  gunzip linux-falcon-v2.8.0.tar.gz 
➜  ls
linux-falcon-v2.8.0.tar
➜  file linux-falcon-v2.8.0.tar 
linux-falcon-v2.8.0.tar: gzip compressed data, was "0.tar", last modified: Thu Jun  7 23:16:15 2018, max compression, from Unix, original size 320321536
➜  file linux-falcon-v2.8.0.tar 
linux-falcon-v2.8.0.tar: POSIX tar archive
```

**Comment by n-riesco** [comment]
The cause of this issue is [a long-standing bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=610679#c62).

I'm planning to documents the steps we follow to make a release and add a note so that we don't use Firefox to download artifacts from CircleCI.
