### ISSUE TITLE
Satellite map doesn't plot anything

### ISSUE THREAD

**Issue by tibaes** [plotly/falcon-sql-client#479]
Using latitude and longitude data I am able to plot using Scatter or Atlas Map, however the type Satellite Map doesn't plot anything at all. I am using the version 2.8.0 on a MacOS 10.12.6.

**Comment by n-riesco** [comment]
To use Satellite Maps in the chart editor, Falcon requires [Mapbox access tokens](https://www.mapbox.com/help/how-access-tokens-work/).

We haven't implemented yet any means to provide these tokens to Falcon.

**Comment by nicolaskruchten** [comment]
@n-riesco we should disable those trace-types in the embedded editor then until this is supported.

**Comment by n-riesco** [comment]
@nicolaskruchten Is there an easy way to do that?

**Comment by nicolaskruchten** [comment]
https://github.com/plotly/react-chart-editor/blob/master/dev/App.js#L44

**Comment by n-riesco** [comment]
@nicolaskruchten Falcon is using `<PlotlyEditor>` at the moment.

**Comment by tibaes** [comment]
@n-riesco thanks for letting me know. I was thinking I missed something.

**Comment by nicolaskruchten** [comment]
On further research, the idea was that if no mapbox token is provided to the editor, those trace-type options should automatically hide...

**Comment by nicolaskruchten** [comment]
Perhaps this is just because we're not using the latest version of the editor here. We should definitely upgrade the editor in the next week :)

**Comment by nicolaskruchten** [comment]
Resolved by bumping `react-chart-editor` to v0.21.1.
