### ISSUE TITLE
Documentation page for Scheduled Queries

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/falcon-sql-client#491]
We will likely need a new page here https://help.plot.ly/database-connectors/ to walk users through the new Scheduled Queries pane and workflow. /cc @cldougl

**Comment by cldougl** [comment]
👍 -- moving over to the [help doc repo](https://github.com/plotly/plotly.github.io/issues/358) to add to the queue: https://github.com/plotly/plotly.github.io/issues/358
