### ISSUE TITLE
Schedule Tab UI QA roundup

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/falcon-sql-client#499]
Let's gather up a few problems here for fixup in a smaller number of PRs than 1-1...

**Comment by mfix22** [comment]
> If I log out of Plotly (or boot Falcon without logging in) and then write a nice fancy query and then hit "schedule" and go through the login process as prompted, I lose my query, it disappears from the query box so I can't schedule it.

Currently when you log in, the enter app is refreshed, which means that no matter what this local state will get reset.

Do you want to resolve this issue and [this](https://github.com/plotly/falcon-sql-client/issues/499#issuecomment-407540216) with a help message and link to log in if the user isn't?

**Comment by nicolaskruchten** [comment]
This one isn't strictly related to the scheduling stuff, but will resolve #479 and I can't seem to do it in my dev environment due to build errors: I'd like to bump the `react-chart-editor` dependency from 0.18 to 0.21 please :)

**Comment by briandennis** [comment]
@nicolaskruchten was your build error similar to [the one on CI](https://circleci.com/gh/plotly/falcon-sql-client/5490)? I can't replicate this locally when building...

**Comment by nicolaskruchten** [comment]
Nope, I'm having issues building the Oracle driver from source.
