### ISSUE TITLE
Updating queries with different numbers and names of columns 

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/falcon-sql-client#507]
Try the following scenario from Falcon with an SQL connector like Postgres:

1. Create a query `select 1 as a` and save it. The result is as expected.
2. Update it to `select 2 as a` and save it. The result is as expected.
3. Update it to `select 3 as b` and save it. Note that the grid on the Plotly side still has the column named `a` and not `b` although the cell value in the row is indeed `3` and the metadata did get updated.
4. Update it to `select 3 as a, 4 as c` and note the pattern: still 1 column only.
5. Update it to `select 3` and note the JSON error without indication of which processing-stage it came from.

A different set of examples is possible when the original dataset has more than 1 column and we try to update it with a dataset with fewer columns: more errors.

These errors don't appear in the webapp-based UI, presumably because it has a different set of API calls when registering a query change, which re-registers the columns?

Heads-up @scjody, this is likely a new blocker for 2.5.0.

**Comment by scjody** [comment]
@nicolaskruchten Is this a regression from 2.4.0? If so can you log an issue in streambed so we can add it to the project?

**Comment by nicolaskruchten** [comment]
FWIW I would consider just raising a user-visible error in cases like this, so that we can move forward with the release, if it's not feasible to actually resolve this fully/properly within the next few days.

**Comment by nicolaskruchten** [comment]
Closed by #511
